sudo: required

services:
  - docker

language: python

dist: xenial
python:
  - "3.9"

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - make docker

after_success:
  - pipenv run codecov

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

branches:
  only:
    - main