dist: xenial

sudo: required

language: python

python:
  - "3.9"

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - make flake

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

branches:
  only:
    - main
